version: '3.8'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    
  vpn-server:
    build: .
    environment:
      DB_HOST: db
    depends_on:
      - db
    ports:
      - "8888:8888"

volumes:
  db_data: